### ISSUE TITLE
Included ruby libraries are all 32-bit

### ISSUE THREAD

**Issue by dseguin** [DFHack/dfhack#987]
After building the develop branch on amd64 using the -DDFHACK_BUILD_ARCH=64 cmake flag, the libruby.so that ends up being installed is 32-bit. The result is working on v0.43.05 64-bit, except for ruby which can't be loaded. Symlinking libruby.so to the system .so causes ruby scripts to hang.

```
$ uname -a
Linux LAPTOP01 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
```

Checklist (-@lethosor):
- [x] Windows
- [x] OS X
- [x] Linux: #989

**Comment by lethosor** [comment]
Yep. We haven't updated the ruby libraries yet. If your system ruby library is 2.x, it probably won't work. You could try ruby 1.8 or 1.9, I suppose.

**Comment by dseguin** [comment]
Cool, I'll try building ruby 1.8 and see if it works. Other than that, I'm surprised at how well it works on df 64-bit already.

**Comment by lethosor** [comment]
Does multicmd work? There could be a bunch of issues with ruby scripts working with structures in 64-bit DF, but multicmd shouldn't run into those (at least if you avoid running ruby scripts with it).

**Comment by dseguin** [comment]
multicmd works fine.

Other ruby scripts hang when trying to interact with the cursor.
i.e. This works:
`superdwarf list` - returns an empty list as expected
But this hangs:
`superdwarf add` with cursor on unit

And something like this `show-unit-syndromes` fails with 
```E: NoMethodError: undefined method `flags1' for nil:NilClass```

**Comment by lethosor** [comment]
Updated title - may as well track the status of the other two platforms here as well.

I'll work on OS X when I get a chance. @jjyg or @BenLubar, a Windows build would be great if you get a chance too.

**Comment by BenLubar** [comment]
@lethosor I can't figure out how to build it for 64-bit. It looks like there's a lot of assembly code specific to various 32-bit compilers. @jjyg may have more luck.

**Comment by lethosor** [comment]
It sounds like fixing this on 64-bit Windows might require updating ruby to 2.x. I'm unclear on exactly what would need to be fixed for that to work.

**Comment by lethosor** [comment]
There's a 64-bit Windows libruby 2.0 that hopefully works (the x86 build of the same one worked for Rumrusher on IRC), and since we support ruby 1.8 and 2 now, I changed the plugin to use the system ruby on 64-bit OS X, which is either 1.8 or 2 depending on the OS X version. Hopefully this is done now, but I'll reopen it if issues turn up with one of those.
