### ISSUE TITLE
removebadthoughts doesn't work in 40.14-r1

### ISSUE THREAD

**Issue by muehlber** [DFHack/dfhack#375]
Hi, I'm getting

[DFHack]# removebadthoughts -n
E: NoMethodError: undefined method `recent_events' for #<DFHack::Unit_TStatus:0xab812300>
 ./hack/scripts/removebadthoughts.rb:10
 ./hack/scripts/removebadthoughts.rb:36:in`[]'
 ./hack/scripts/removebadthoughts.rb:36
 ./hack/scripts/removebadthoughts.rb:35:in `each'
 ./hack/scripts/removebadthoughts.rb:35
 (eval):1:in`load'
 (eval):1
 (eval):1:in `catch'

I guess it's a known issue and a result of the switch to personality-dependent emotion/circumstance pairs? Maybe there could be a command to quickly set the longer-term stress level of our minions to 0?
