### ISSUE TITLE
Broken script: "ban-cooking tallow" gives error message, and does not function

### ISSUE THREAD

**Issue by AncalagonX** [DFHack/dfhack#1293]
I followed [this post](https://github.com/DFHack/dfhack/issues/295#issuecomment-173707475) from @BenLubar , however it throws this error and does not function:

```
[DFHack]# ban-cooking tallow
E: NoMethodError: undefined method `&' for :Cook:Symbol
 hack/scripts/ban-cooking.rb:23:in `block in <top (required)>'
 hack/scripts/ban-cooking.rb:22:in `times'
 hack/scripts/ban-cooking.rb:22:in `<top (required)>'
 eval:2:in `load'
 eval:2:in `block in <main>'
 eval:2:in `catch'
 eval:2:in `<main>'
[DFHack]#
```

Thanks for handling this whenever there's time. Tallow management is pretty annoying for the first few years of fortress-running.

**Comment by lethosor** [comment]
This was likely broken by https://github.com/DFHack/df-structures/commit/238b3053f37feffdc0ab2d5d4415987c33a5d0e4, which is pretty recent.
From a quick glance, I think you can fix it by changing `& 1` on that line (it's the only occurrence in ban-cooking.rb) with `== :Cook`.
However, it looks like the script assumes that exc_types contains bitfields, when it actually just contains single exclusions. This can be verified with `lua ~df.global.ui.kitchen.exc_types` after forbidding cooking and brewing the same ingredient in the z-kitchen screen. @BenLubar, mind taking a look to see what else needs to be adjusted?
Thanks for the recent reports, by the way.

**Comment by AncalagonX** [comment]
>Thanks for the recent reports, by the way.

@lethosor Thanks for the thanks, it really motivates me to come back and post more issues when they crop up! I also saw the ```good first issue``` tag on some issue submissions and I think that's a _great_ idea for encouraging repeat issue posters. You guys seem to work hard at establishing a good community culture here, and it really shows.

**Comment by lethosor** [comment]
That tag is actually supposed to be good issues for new contributors to work on. That specific name causes GitHub to list those issues elsewhere for people looking for projects to contribute to in general. (Some of my own have that tag, and I've opened a decent number of issues.)
